version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - ./.env.postgres  # Указываем путь к файлу с переменными для PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped  # Политика перезапуска

  bybit-data-fetch:
    build:
      context: ./bybitDataFetch
      dockerfile: Dockerfile
    container_name: bybit_data_fetch
    env_file:
      - ./bybitDataFetch/.env  # Используем существующий .env для микросервиса
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"     # Порт хоста: Порт контейнера
    networks:
      - app_network
    volumes:
      - app_logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
    external: false
  app_logs:
    external: false

networks:
  app_network:
    driver: bridge