version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - ./.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  bybit-data-fetch:
    build:
      context: ./bybitDataFetch
      dockerfile: Dockerfile
    container_name: bybit_data_fetch
    env_file:
      - ./bybitDataFetch/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"
    networks:
      - app_network
    volumes:
      - app_logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
    external: false
  app_logs:
    external: false

networks:
  app_network:
    driver: bridge
